// format
// word: str
// definition: str

const content = [
    {
        word: 'ATP',
        definition: 'ATP is short for adenosine triphosphate, and is a form of energy for cells. It\'s generated using cellular respiration.'
    },
    {
        word: 'Carbon Dioxide',
        definition: 'A waste product produced by cellular respiration. The chemical compound is CO2.'
    },
    {
        word: 'Pyruvate',
        definition: 'A chemical compound outputted by glycolysis. Gives energy to Krebs cycle.'
    },
    {
        word: 'Glycolysis',
        definition: 'Process of breaking glucose down into pyruvate.'
    },
    {
        word: 'Krebs Cycle',
        definition: 'Releases stored energy using pyruvate'
    },
    {
        word: 'Electron Transport',
        definition: 'Uses ATP to produce more ATP for cells. Uses ATP previously generated by Krebs cycle and glycolysis to function.'
    },
];
export default content;